---
title: "AN588_Assignment_2"
author: "Yongliang Cen"
date: "2025-02-06"
output: html_document
---
## Peer Commentary: For formatting, don't forget to use the Cayman theme from the Prettydoc package, organizng the headers in a table of contents!

## Peer Commentary: Don't forget to add you picture of your favorite monkey! I used the "KnitR" command within an R chunk. My file was a JPG.

### Every Saturday morning, at the same time, a primatologist goes and sits in the forest to listen for titi monkey calls, counting the number of calls they hear in a 2 hour window from 5am to 7am. Based on previous knowledge, she believes that the mean number of calls she will hear in that time is exactly 15. Let X represent the appropriate Poisson random variable of the number of calls heard in each monitoring session.
```{r}
# What is the probability that she will hear more than 8 calls during any given session?
p_more_than_8 <- ppois(8, lambda = 15, lower.tail = FALSE)

# What is the probability that she will hear no calls in a session?
p_0_calls <- dpois(0, lambda = 15)

# What is the probability that she will hear exactly 3 calls in a session?
p_is_3 <- dpois(3, lambda = 15)

# Plot the relevant Poisson mass function over the values in range 0 ≤ 𝑥 ≤ 30.

x <- 0:30
l = 15
probset <- dpois(x = x, lambda = l)
barplot(probset, names.arg = x, space = 0, xlab = "x", ylab = "Pr(X = x)", main = "Probability Mass Function")

# Simulate 104 results from this distribution (i.e., 2 years of Saturday monitoring sessions).
simulation <- rpois(104, lambda = 15)


# Plot the simulated results using hist() and use xlim() to set the horizontal limits to be from 0 to 30. How does your histogram compare to the shape of the probability mass function you plotted above?

hist(simulation, xlim = c(0, 30))

#Response to question: The histogram of the simulated results looks very similar to the theoretical Poisson probability mass function. Both plots show that the distribution is unimodal with the highest frequency around 15 calls and tapering off on both sides. Although the simulation (with 104 sessions) shows some random fluctuations because of the limited sample size, its overall shape confirms the expected Poisson pattern. With a larger number of simulations, the histogram would converge even more closely to the PMF
```
## Peer Commentary: Very well expalined, and good job! Don't forget to add your 5 challenges! Concerning your 104 result simulation, I thought you putting the entire function into one "simulation" variable was very effective, because I also needed to do that to prevent syntax errors. 
